### ISSUE TITLE
No indicator for focused unread items

### ISSUE THREAD

**Issue by moddedBear** [joelchrono12/freshrss-nord-theme#1]
Just noticed a small issue that affects keyboard navigation. When moving focus up and down with keyboard shortcuts (n and p by default) there's no way to tell which article is currently focused if the article is unread. Looks like it tries to bold the title, but unread articles already have their titles bolded.

**Comment by joelchrono12** [comment]
On 22/06/02 03:33PM, moddedBear wrote:
>Just noticed a small issue that affects keyboard navigation. When 
>moving focus up and down with keyboard shortcuts (n and p by default) 
>there's no way to tell which article is currently focused if the 
>article is unread. Looks like it tries to bold the title, but unread 
>articles already have their titles bolded.

Hey, this should be fixed now, so pull the changes and check it out.
